#!/usr/bin/env bash

# Setup data files

MNIST_PATH=data/mnist
mkdir -p $MNIST_PATH

wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz -O $MNIST_PATH/training_imgs.gz
gunzip $MNIST_PATH/training_imgs.gz
wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz -O $MNIST_PATH/training_labels.gz
gunzip $MNIST_PATH/training_labels.gz
wget http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz -O $MNIST_PATH/test_imgs.gz
gunzip $MNIST_PATH/test_imgs.gz
wget http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz -O $MNIST_PATH/test_labels.gz
gunzip $MNIST_PATH/test_labels.gz

echo "MNIST downloaded!"
